"""phase4 org settings and shift org id

Revision ID: fd49e1a252de
Revises: abfb0859d813
Create Date: 2026-04-04 19:51:02.062444+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd49e1a252de'
down_revision: Union[str, None] = 'abfb0859d813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('geo_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_finish_hours', sa.Integer(), nullable=False),
    sa.Column('max_pause_minutes', sa.Integer(), nullable=True),
    sa.Column('max_pauses_per_shift', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_settings_organization_id'), 'organization_settings', ['organization_id'], unique=True)
    op.add_column('shifts', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'shifts', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_column('shifts', 'organization_id')
    op.drop_index(op.f('ix_organization_settings_organization_id'), table_name='organization_settings')
    op.drop_table('organization_settings')
    # ### end Alembic commands ###
